### ISSUE TITLE
The messy exploration notebook

### ISSUE THREAD

**Issue by wmy10128** [hasibzunair/adversarial-lesions#10]
Hi,  i am  running  the  eda.ipynb, but there is nothing in the  dir :  /outputs/auc, don't  have 1.pkl 2.pkl ...... ,please help me ,thank you very much
1.there is no output  after  running  the follow code:
```
import pickle
def save_obj(obj, name):
    with open('{}/'.format(OUTPUTS) + name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)
def load_obj(name):
    with open('{}/'.format(OUTPUTS) + name + '.pkl', 'rb') as f:
        return pickle.load(f)
def get_unique(arr):

  arr = set(arr)
  return arr

```
Then go on，

```
exp1 = load_obj('1')
exp2 = load_obj('2')
exp3 = load_obj('3')
exp4 = load_obj('4')
exp1 
```

the Error is： FileNotfounderror: no such file or directory : '/home/adversarial-lesions/outputs/auc/1.pkl

**Comment by hasibzunair** [comment]
Hi, sorry for the late reply. You need to train the models to get those files. I used this notebook when comparing different models, so I did not add those files in this repo.
