### ISSUE TITLE
Urgent : problem with the training source code

### ISSUE THREAD

**Issue by pa0l09405** [hasibzunair/adversarial-lesions#4]
Hi,
i'm following all the steps in the readme file to reply your work in google colab. I'm running the notebook train_cyclegan.ipynb. But it doesn't find the subfolders testA and testB under the folder /isic2016gan, because in the previous step the script 'data_process_gan.py' doesn't create these subfolders, it creates just trainA and trainB subfolders, but not testA and testB. So I'm stopped, I don't know how to fix.
Please help me soon, 
thanks in advance :)

**Comment by pa0l09405** [comment]
This is my output 
<img width="653" alt="issue_github" src="https://user-images.githubusercontent.com/12819181/83860305-65163380-a71f-11ea-88e4-d40effe4a8df.png">

**Comment by hasibzunair** [comment]
Hello,

Thanks for your interest in this work. Yes, the script does not make testA and testB subfolders. For my experiments I did that manually. You can simply make two folders where you have trainA and trainB and name them testA and testB. After that, you can add an image for each domain in those folders. This is done to see the training process(you will find an `images` folder on `model_path`). Basically testA will contain an image from trainA, same thing for testB. 

Hope that answers you're question.

**Comment by hasibzunair** [comment]
Please close the issue when it is resolved. Thanks!

**Comment by pa0l09405** [comment]
Hi, yes thanks u so much for the help ;)
