### ISSUE TITLE
Excecution of multiple notebooks in colab

### ISSUE THREAD

**Issue by pa0l09405** [hasibzunair/adversarial-lesions#5]
Hi, 
i need an info. In your project there are multiple notebooks. How can I excecute them on Cloud (I'm using Google Colab), keeping them separated ?
I don't know how to share the filesystem among them, so I'm creating one single notebook containing the source code of all of them, and this is so little efficient.
How can I link the data among the notebooks, and how can I excecute one of them in background, if possible ?
Thanks :)

**Comment by hasibzunair** [comment]
Hi,

Each of the notebooks are independent and you can run them in the sequence given. You can make separate Colab notebooks and then run them. I am not entirely sure what you are looking for. Closing this issue since it is a Colab usage problem.
