### ISSUE TITLE
how to use the pre-trained weights about  generate.h5 and melanet.h5

### ISSUE THREAD

**Issue by wmy10128** [hasibzunair/adversarial-lesions#9]

**Comment by wmy10128** [comment]
excuse me ,I have run the tain_ISIC_2016.ipynb, and it was run 100epoches,the acc of the last epoch is 0.8948986 .but I don't know when and how to use this two pre-trained weights,please help me ,thank you very much

**Comment by hasibzunair** [comment]
Hi, the pre-trained weights are there if you do not want to train the models and evaluate. The `generator.h5` is the one after training Cycle-GAN. The `MelaNet.h5` is the trained classification model on the upsampled dataset using `generator.h5` to synthesize new samples. 

See https://github.com/hasibzunair/adversarial-lesions/blob/master/isic2016_scripts/train_cyclegan.ipynb and https://github.com/hasibzunair/adversarial-lesions/blob/master/isic2016_scripts/upsampler.ipynb for details.
